update to 2.0.20

diff --git a/kdumpctl b/kdumpctl
--- a/kdumpctl
+++ b/kdumpctl
@@ -4,6 +4,7 @@ KEXEC=/sbin/kexec
 KDUMP_KERNELVER=""
 KDUMP_COMMANDLINE=""
 KEXEC_ARGS=""
+KDUMP_FILE_LOAD=""
 KDUMP_CONFIG_FILE="/etc/kdump.conf"
 MKDUMPRD="/sbin/mkdumprd -f"
 DRACUT_MODULES_FILE="/usr/lib/dracut/modules.txt"
@@ -94,7 +95,7 @@ rebuild_fadump_initrd()
 	# this file tells the initrd is fadump enabled
 	touch /tmp/fadump.initramfs
 	target_initrd_tmp="$TARGET_INITRD.tmp"
-	$MKDUMPRD $target_initrd_tmp --rebuild $TARGET_INITRD --kver $kdump_kver \
+	$MKDUMPRD $target_initrd_tmp --rebuild $DEFAULT_INITRD_BAK --kver $kdump_kver \
 		-i /tmp/fadump.initramfs /etc/fadump.initramfs
 	if [ $? != 0 ]; then
 		echo "mkdumprd: failed to rebuild initrd with fadump support" >&2
@@ -110,6 +111,12 @@ rebuild_fadump_initrd()
 	return 0
 }
 
+check_earlykdump_is_enabled()
+{
+	grep -q -w "rd.earlykdump" /proc/cmdline
+	return $?
+}
+
 rebuild_kdump_initrd()
 {
 	$MKDUMPRD $TARGET_INITRD $kdump_kver
@@ -118,11 +125,20 @@ rebuild_kdump_initrd()
 		return 1
 	fi
 
+	if check_earlykdump_is_enabled; then
+		echo "Tips: If early kdump is enabled, also require rebuilding the system initramfs to make the changes take effect for early kdump."
+	fi
+
 	return 0
 }
 
 rebuild_initrd()
 {
+	if [[ ! -w "$KDUMP_BOOTDIR" ]];then
+		echo "$KDUMP_BOOTDIR does not have write permission. Can not rebuild $TARGET_INITRD"
+		return 1
+	fi
+
 	if [ $DEFAULT_DUMP_MODE == "fadump" ]; then
 		rebuild_fadump_initrd
 	else
@@ -228,13 +244,15 @@ check_config()
 		case "$config_opt" in
 		\#* | "")
 			;;
-		raw|ext2|ext3|ext4|minix|btrfs|xfs|nfs|ssh|sshkey|path|core_collector|kdump_post|kdump_pre|extra_bins|extra_modules|default|force_rebuild|force_no_rebuild|dracut_args|fence_kdump_args|fence_kdump_nodes)
+		raw|ext2|ext3|ext4|minix|btrfs|xfs|nfs|ssh|sshkey|path|core_collector|kdump_post|kdump_pre|extra_bins|extra_modules|failure_action|default|final_action|force_rebuild|force_no_rebuild|dracut_args|fence_kdump_args|fence_kdump_nodes)
 			# remove inline comments after the end of a directive.
-			config_val=$(strip_comments $config_val)
 			[ -z "$config_val" ] && {
 				echo "Invalid kdump config value for option $config_opt."
 				return 1;
 			}
+			if [ -d "/proc/device-tree/ibm,opal/dump" ] && [ "$config_opt" == "raw" ]; then
+				echo "WARNING: Won't capture opalcore when 'raw' dump target is used."
+			fi
 			;;
 		net|options|link_delay|disk_timeout|debug_mem_level|blacklist)
 			echo "Deprecated kdump config option: $config_opt. Refer to kdump.conf manpage for alternatives."
@@ -245,9 +263,10 @@ check_config()
 			return 1;
 			;;
 		esac
-	done < $KDUMP_CONFIG_FILE
+	done <<< "$(read_strip_comments $KDUMP_CONFIG_FILE)"
 
-	check_default_config || return 1
+	check_failure_action_config || return 1
+	check_final_action_config || return 1
 
 	check_fence_kdump_config || return 1
 
@@ -283,16 +302,31 @@ get_pcs_cluster_modified_files()
 
 setup_initrd()
 {
+	KDUMP_BOOTDIR=$(check_boot_dir "${KDUMP_BOOTDIR}")
+
+	if [ -z "$KDUMP_KERNELVER" ]; then
+		kdump_kver=`uname -r`
+	else
+		kdump_kver=$KDUMP_KERNELVER
+	fi
+
+	kdump_kernel="${KDUMP_BOOTDIR}/${KDUMP_IMG}-${kdump_kver}${KDUMP_IMG_EXT}"
+
 	DEFAULT_INITRD="${KDUMP_BOOTDIR}/initramfs-`uname -r`.img"
 	DEFAULT_INITRD_BAK="${KDUMP_BOOTDIR}/.initramfs-`uname -r`.img.default"
 	if [ $DEFAULT_DUMP_MODE == "fadump" ]; then
 		TARGET_INITRD="$DEFAULT_INITRD"
-		if [ ! -s "$TARGET_INITRD" ]; then
-			echo "Error: No initrd found to rebuild!"
-			return 1
-		fi
+
+		# backup initrd for reference before replacing it
+		# with fadump aware initrd
+		backup_default_initrd
 	else
 		TARGET_INITRD="${KDUMP_BOOTDIR}/initramfs-${kdump_kver}kdump.img"
+
+		# check if a backup of default initrd exists. If yes,
+		# it signifies a switch from fadump mode. So, restore
+		# the backed up default initrd.
+		restore_default_initrd
 	fi
 }
 
@@ -313,15 +347,49 @@ check_files_modified()
 	files="$KDUMP_CONFIG_FILE $kdump_kernel $EXTRA_BINS $CORE_COLLECTOR"
 	[[ -e /etc/fstab ]] && files="$files /etc/fstab"
 
+	# Check for any updated extra module
+	EXTRA_MODULES="$(grep ^extra_modules $KDUMP_CONFIG_FILE | sed 's/^extra_modules\s*//')"
+	if [ -n "$EXTRA_MODULES" ]; then
+		if [ -e /lib/modules/$kdump_kver/modules.dep ]; then
+			files="$files /lib/modules/$kdump_kver/modules.dep"
+		fi
+		for _module in $EXTRA_MODULES; do
+			_module_file="$(modinfo --set-version "$kdump_kver" --filename "$_module" 2>/dev/null)"
+			if [[ $? -eq 0 ]]; then
+				files="$files $_module_file"
+				for _dep_modules in $(modinfo -F depends $_module | tr ',' ' '); do
+				    files="$files $(modinfo --set-version "$kdump_kver" --filename $_dep_modules 2>/dev/null)"
+				done
+			else
+				# If it's not a module nor builtin, give an error
+				if ! ( modprobe --set-version "$kdump_kver" --dry-run "$_module" &>/dev/null ); then
+					echo "Module $_module not found"
+				fi
+			fi
+		done
+	fi
+
 	check_exist "$files" && check_executable "$EXTRA_BINS"
 	[ $? -ne 0 ] && return 2
 
 	for file in $files; do
-		time_stamp=`stat -c "%Y" $file`
-		if [ "$time_stamp" -gt "$image_time" ]; then
-			modified_files="$modified_files $file"
+		if [ -e "$file" ]; then
+			time_stamp=`stat -c "%Y" $file`
+			if [ "$time_stamp" -gt "$image_time" ]; then
+				modified_files="$modified_files $file"
+			fi
+			if [ -L "$file" ]; then
+				file=$(readlink -m $file)
+				time_stamp=`stat -c "%Y" $file`
+				if [ "$time_stamp" -gt "$image_time" ]; then
+					modified_files="$modified_files $file"
+				fi
+			fi
+		else
+			echo "$file doesn't exist"
 		fi
 	done
+
 	if [ -n "$modified_files" ]; then
 		echo "Detected change(s) in the following file(s):"
 		echo -n "  "; echo "$modified_files" | sed 's/\s/\n  /g'
@@ -336,6 +404,9 @@ check_dump_fs_modified()
 	local _old_dev _old_mntpoint _old_fstype
 	local _new_dev _new_mntpoint _new_fstype
 	local _target _path _dracut_args
+	local _target_drivers _module_name _module_filename
+
+	local _old_drivers="$(lsinitrd $TARGET_INITRD -f /usr/lib/dracut/hostonly-kernel-modules.txt | tr '\n' ' ')"
 
 	# No need to check in case of mount target specified via "dracut_args".
 	if is_mount_in_dracut_args; then
@@ -363,6 +434,36 @@ check_dump_fs_modified()
 			return 2
 		fi
 	fi
+
+	_record_block_drivers() {
+		local _drivers
+		if [[ -b /dev/block/$1 ]]; then
+			_drivers=$(udevadm info -a "/dev/block/$1" | sed -n 's/\s*DRIVERS=="\(\S\+\)"/\1/p')
+		fi
+		if [[ -b $1 ]]; then
+			_drivers=$(udevadm info -a "$1" | sed -n 's/\s*DRIVERS=="\(\S\+\)"/\1/p')
+		fi
+		for _driver in $_drivers; do
+			if ! [[ " $_target_drivers " == *" $_driver "* ]]; then
+				_target_drivers="$_target_drivers $_driver"
+			fi
+		done
+		return 1
+	}
+
+	check_block_and_slaves_all _record_block_drivers "$(get_maj_min "$_target")"
+	for _driver in $_target_drivers; do
+		# Skip deprecated/invalid driver name or built-in module
+		_module_name=$(modinfo --set-version "$kdump_kver" -F name $_driver 2>/dev/null)
+		_module_filename=$(modinfo --set-version "$kdump_kver" -n $_driver 2>/dev/null)
+		if [ $? -ne 0 ] || [ -z "$_module_name" ] || [[ "$_module_filename" = *"(builtin)"* ]]; then
+			continue
+		fi
+		if ! [[ " $_old_drivers " == *" $_module_name "* ]]; then
+			echo "Detected change in block device driver, new loaded module: $_module_name"
+			return 1
+		fi
+	done
 
 	if [[ $(expr substr $_new_fstype 1 3) = "nfs" ]];then
 		_new_dev=$_target
@@ -465,31 +566,6 @@ check_wdt_modified()
 	return 1
 }
 
-check_kmodules_modified()
-{
-	# always sort again to avoid LANG/LC inconsistent problem
-	local _old_modules="$(lsinitrd $TARGET_INITRD -f /usr/lib/dracut/loaded-kernel-modules.txt | sort)"
-	local _new_modules="$(get_loaded_kernel_modules | sort)"
-
-	[[ -z $_old_modules ]] && echo "Warning: Previous loaded kernel module list is absent or empty"
-
-	local _added_modules=$(comm -13 <(echo "$_old_modules") <(echo "$_new_modules"))
-	local _dropped_modules=$(comm -23 <(echo "$_old_modules") <(echo "$_new_modules"))
-
-	if [ "$_old_modules" != "$_new_modules" ]; then
-		echo "Detected change(s) of loaded kernel modules list:"
-		[[ -n $_added_modules ]] && for _module in $_added_modules; do
-			echo "	+$_module"
-		done
-		[[ -n $_dropped_modules ]] && for _module in $_dropped_modules; do
-			echo "	-$_module"
-		done
-		return 1
-	fi
-
-	return 0
-}
-
 # returns 0 if system is not modified
 # returns 1 if system is modified
 # returns 2 if system modification is invalid
@@ -517,32 +593,18 @@ check_system_modified()
 		return 1
 	fi
 
-	check_kmodules_modified
-	if [ $? -ne 0 ]; then
-		return 1
-	fi
-
 	return 0
 }
 
 check_rebuild()
 {
-	local extra_modules
 	local capture_capable_initrd="1"
 	local _force_rebuild force_rebuild="0"
 	local _force_no_rebuild force_no_rebuild="0"
 	local ret system_modified="0"
 
-	KDUMP_BOOTDIR=$(check_boot_dir "${KDUMP_BOOTDIR}")
-
-	if [ -z "$KDUMP_KERNELVER" ]; then
-		kdump_kver=`uname -r`
-	else
-		kdump_kver=$KDUMP_KERNELVER
-	fi
-
-	kdump_kernel="${KDUMP_BOOTDIR}/${KDUMP_IMG}-${kdump_kver}${KDUMP_IMG_EXT}"
 	setup_initrd
+
 	if [ $? -ne 0 ]; then
 		return 1
 	fi
@@ -575,10 +637,6 @@ check_rebuild()
 		return 0
 	fi
 
-	#will rebuild every time if extra_modules are specified
-	extra_modules=`grep ^extra_modules $KDUMP_CONFIG_FILE`
-	[ -n "$extra_modules" ] && force_rebuild="1"
-
 	#check to see if dependent files has been modified
 	#since last build of the image file
 	if [ -f $TARGET_INITRD ]; then
@@ -599,8 +657,6 @@ check_rebuild()
 		system_modified="1"
 	fi
 
-	handle_mode_switch
-
 	if [ $image_time -eq 0 ]; then
 		echo  -n "No kdump initial ramdisk found."; echo
 	elif [ "$capture_capable_initrd" == "0" ]; then
@@ -611,11 +667,6 @@ check_rebuild()
 		:
 	else
 		return 0
-	fi
-
-	if [[ ! -w "$KDUMP_BOOTDIR" ]];then
-		echo "$KDUMP_BOOTDIR does not have write permission. Can not rebuild $TARGET_INITRD"
-		return 1
 	fi
 
 	echo "Rebuilding $TARGET_INITRD"
@@ -631,11 +682,8 @@ load_kdump()
 	KEXEC_ARGS=$(prepare_kexec_args "${KEXEC_ARGS}")
 	KDUMP_COMMANDLINE=$(prepare_cmdline "${KDUMP_COMMANDLINE}" "${KDUMP_COMMANDLINE_REMOVE}" "${KDUMP_COMMANDLINE_APPEND}")
 
-	# For secureboot enabled machines, use new kexec file based syscall.
-	# Old syscall will always fail as it does not have capability to
-	# to kernel signature verification.
-	if is_secure_boot_enforced; then
-		echo "Secure Boot is enabled. Using kexec file based syscall."
+	if [ "$KDUMP_FILE_LOAD" == "on" ]; then
+		echo "Using kexec file based syscall."
 		KEXEC_ARGS="$KEXEC_ARGS -s"
 	fi
 
@@ -647,6 +695,9 @@ load_kdump()
 		return 0
 	else
 		echo "kexec: failed to load kdump kernel" >&2
+		if [ "$KDUMP_FILE_LOAD" == "on" ]; then
+			echo "kexec_file_load() failed, please try kexec_load()" >&2
+		fi
 		return 1
 	fi
 }
@@ -657,7 +708,6 @@ check_ssh_config()
 		case "$config_opt" in
 		sshkey)
 			# remove inline comments after the end of a directive.
-			config_val=$(strip_comments $config_val)
 			if [ -f "$config_val" ]; then
 				# canonicalize the path
 				SSH_KEY_LOCATION=$(/usr/bin/readlink -m $config_val)
@@ -666,17 +716,15 @@ check_ssh_config()
 			fi
 			;;
 		path)
-			config_val=$(strip_comments $config_val)
 			SAVE_PATH=$config_val
 			;;
 		ssh)
-			config_val=$(strip_comments $config_val)
 			DUMP_TARGET=$config_val
 			;;
 		*)
 			;;
 		esac
-	done < $KDUMP_CONFIG_FILE
+	done <<< "$(read_strip_comments $KDUMP_CONFIG_FILE)"
 
 	#make sure they've configured kdump.conf for ssh dumps
 	local SSH_TARGET=`echo -n $DUMP_TARGET | sed -n '/.*@/p'`
@@ -686,13 +734,60 @@ check_ssh_config()
 	return 0
 }
 
+# ipv6 host address may takes a long time to be ready.
+# Instead of checking against ipv6 address, we just check the network reachable
+# by the return val of 'ssh'
+check_and_wait_network_ready()
+{
+	local start_time=$(date +%s)
+	local warn_once=1
+	local cur
+	local diff
+	local retval
+	local errmsg
+
+	while true; do
+		errmsg=$(ssh -i $SSH_KEY_LOCATION -o BatchMode=yes $DUMP_TARGET mkdir -p $SAVE_PATH 2>&1)
+		retval=$?
+
+		# ssh exits with the exit status of the remote command or with 255 if an error occurred
+		if [ $retval -eq 0 ]; then
+			return 0
+		elif [ $retval -ne 255 ]; then
+			echo "Could not create $DUMP_TARGET:$SAVE_PATH, you should check the privilege on server side"  >&2
+			return 1
+		fi
+
+		# if server removes the authorized_keys or, no /root/.ssh/kdump_id_rsa
+		echo $errmsg | grep -q "Permission denied\|No such file or directory\|Host key verification failed"
+		if [ $? -eq 0 ]; then
+			echo "Could not create $DUMP_TARGET:$SAVE_PATH, you probably need to run \"kdumpctl propagate\""  >&2
+			return 1
+		fi
+
+		if [ $warn_once -eq 1 ]; then
+			echo "Network dump target is not usable, waiting for it to be ready"
+			warn_once=0
+		fi
+		echo -n .
+
+		cur=$(date +%s)
+		let "diff = $cur - $start_time"
+		# 60s time out
+		if [ $diff -gt 180 ]; then
+			break;
+		fi
+		sleep 1
+	done
+
+	echo "Could not create $DUMP_TARGET:$SAVE_PATH, ipaddr is not ready yet. You should check network connection"  >&2
+	return 1
+}
+
 check_ssh_target()
 {
-	local _ret
-	ssh -q -i $SSH_KEY_LOCATION -o BatchMode=yes $DUMP_TARGET mkdir -p $SAVE_PATH
-	_ret=$?
-	if [ $_ret -ne 0 ]; then
-		echo "Could not create $DUMP_TARGET:$SAVE_PATH, you probably need to run \"kdumpctl propagate\""  >&2
+	check_and_wait_network_ready
+	if [ $? -ne 0 ]; then
 		return 1
 	fi
 	return 0
@@ -742,20 +837,6 @@ show_reserved_mem()
     echo "Reserved "$mem_mb"MB memory for crash kernel"
 }
 
-handle_mode_switch()
-{
-	if [ "$DEFAULT_DUMP_MODE" == "fadump" ]; then
-		# backup initrd for reference before replacing it
-		# with fadump aware initrd
-		backup_default_initrd
-	else
-		# check if a backup of default initrd exists. If yes,
-		# it signifies a switch from fadump mode. So, restore
-		# the backed up default initrd.
-		restore_default_initrd
-	fi
-}
-
 check_current_fadump_status()
 {
 	# Check if firmware-assisted dump has been registered.
@@ -786,6 +867,11 @@ save_raw()
 		echo "raw partition $raw_target not found"
 		return 1
 	}
+	check_fs=$(lsblk --nodeps -npo FSTYPE $raw_target)
+	if [[ $(echo $check_fs | wc -w) -ne 0 ]]; then
+		echo "Warning: Detected '$check_fs' signature on $raw_target, data loss is expected."
+		return 0
+	fi
 	kdump_dir=`grep ^path $KDUMP_CONFIG_FILE | cut -d' '  -f2-`
 	if [ -z "${kdump_dir}" ]; then
 		coredir="/var/crash/`date +"%Y-%m-%d-%H:%M"`"
@@ -810,15 +896,6 @@ save_raw()
 	return 0
 }
 
-is_dump_target_configured()
-{
-	local _target
-
-	_target=$(egrep "^ext[234]|^xfs|^btrfs|^minix|^raw|^ssh|^nfs" /etc/kdump.conf)
-
-	[ -n "$_target" ]
-}
-
 local_fs_dump_target()
 {
 	local _target
@@ -833,7 +910,11 @@ path_to_be_relabeled()
 {
 	local _path _target _mnt="/" _rmnt
 
-	if is_dump_target_configured; then
+	if is_user_configured_dump_target; then
+		if is_mount_in_dracut_args; then
+		    return;
+		fi
+
 		_target=$(local_fs_dump_target)
 		if [[ -n "$_target" ]]; then
 			_mnt=$(findmnt -k -f -n -r -o TARGET $_target)
@@ -845,9 +926,6 @@ path_to_be_relabeled()
 		fi
 	fi
 
-	if is_mount_in_dracut_args; then
-		return;
-	fi
 	_path=$(get_save_path)
 	# if $_path is masked by other mount, we will not relabel it.
 	_rmnt=$(df $_mnt/$_path 2>/dev/null | tail -1 | awk '{ print $NF }')
@@ -928,20 +1006,51 @@ start_dump()
 	return $?
 }
 
-check_default_config()
+check_failure_action_config()
 {
 	local default_option
+	local failure_action
+	local option="failure_action"
 
 	default_option=$(awk '$1 ~ /^default$/ {print $2;}' $KDUMP_CONFIG_FILE)
-	if [ -z "$default_option" ]; then
+	failure_action=$(awk '$1 ~ /^failure_action$/ {print $2;}' $KDUMP_CONFIG_FILE)
+
+	if [ -z "$failure_action" -a -z "$default_option" ]; then
+		return 0
+	elif [ -n "$failure_action" -a -n "$default_option" ]; then
+		echo "Cannot specify 'failure_action' and 'default' option together"
+		return 1
+	fi
+
+	if [ -n "$default_option" ]; then
+		option="default"
+		failure_action="$default_option"
+	fi
+
+	case "$failure_action" in
+	  reboot|halt|poweroff|shell|dump_to_rootfs)
+		return 0
+	  ;;
+	  *)
+		echo $"Usage kdump.conf: $option {reboot|halt|poweroff|shell|dump_to_rootfs}"
+		return 1
+	esac
+}
+
+check_final_action_config()
+{
+	local final_action
+
+	final_action=$(awk '$1 ~ /^final_action$/ {print $2;}' $KDUMP_CONFIG_FILE)
+	if [ -z "$final_action" ]; then
 		return 0
 	else
-		case "$default_option" in
-		  reboot|halt|poweroff|shell|dump_to_rootfs)
+		case "$final_action" in
+		  reboot|halt|poweroff)
 			return 0
 		  ;;
 		  *)
-			echo $"Usage kdump.conf: default {reboot|halt|poweroff|shell|dump_to_rootfs}"
+			echo $"Usage kdump.conf: final_action {reboot|halt|poweroff}"
 			return 1
 		esac
 	fi
@@ -999,6 +1108,42 @@ start()
 	echo "Starting kdump: [OK]"
 }
 
+reload()
+{
+	check_current_status
+	if [ $? -ne 0 ]; then
+		echo "Kdump was not running: [WARNING]"
+	fi
+
+	if [ $DEFAULT_DUMP_MODE == "fadump" ]; then
+		reload_fadump
+		return $?
+	else
+		stop_kdump
+	fi
+
+	if [ $? -ne 0 ]; then
+		echo "Stopping kdump: [FAILED]"
+		return 1
+	fi
+
+	echo "Stopping kdump: [OK]"
+
+	setup_initrd
+	if [ $? -ne 0 ]; then
+		echo "Starting kdump: [FAILED]"
+		return 1
+	fi
+
+	start_dump
+	if [ $? -ne 0 ]; then
+		echo "Starting kdump: [FAILED]"
+		return 1
+	fi
+
+	echo "Starting kdump: [OK]"
+}
+
 stop_fadump()
 {
 	echo 0 > $FADUMP_REGISTER_SYS_NODE
@@ -1013,7 +1158,7 @@ stop_fadump()
 
 stop_kdump()
 {
-	if is_secure_boot_enforced; then
+	if [ "$KDUMP_FILE_LOAD" == "on" ]; then
 		$KEXEC -s -p -u
 	else
 		$KEXEC -p -u
@@ -1026,6 +1171,26 @@ stop_kdump()
 
 	echo "kexec: unloaded kdump kernel"
 	return 0
+}
+
+reload_fadump()
+{
+	echo 1 > $FADUMP_REGISTER_SYS_NODE
+	if [ $? == 0 ]; then
+		echo "fadump: re-registered successfully"
+		return 0
+	else
+		# FADump could fail on older kernel where re-register
+		# support is not enabled. Try stop/start from userspace
+		# to handle such scenario.
+		stop_fadump
+		if [ $? == 0 ]; then
+			start_fadump
+			return $?
+		fi
+	fi
+
+	return 1
 }
 
 stop()
@@ -1043,6 +1208,28 @@ stop()
 
 	echo "Stopping kdump: [OK]"
 	return 0
+}
+
+rebuild() {
+	check_config
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
+	if check_ssh_config; then
+		if ! check_ssh_target; then
+			return 1
+		fi
+	fi
+
+	setup_initrd
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
+	echo "Rebuilding $TARGET_INITRD"
+	rebuild_initrd
+	return $?
 }
 
 if [ ! -f "$KDUMP_CONFIG_FILE" ]; then
@@ -1082,9 +1269,15 @@ main ()
 		esac
 		exit $EXIT_CODE
 		;;
+	  reload)
+		reload
+		;;
 	  restart)
 		stop
 		start
+		;;
+	  rebuild)
+		rebuild
 		;;
 	  condrestart)
 		;;
@@ -1095,7 +1288,7 @@ main ()
 		show_reserved_mem
 		;;
 	  *)
-		echo $"Usage: $0 {start|stop|status|restart|propagate|showmem}"
+		echo $"Usage: $0 {start|stop|status|restart|reload|rebuild|propagate|showmem}"
 		exit 1
 	esac
 }
